name = "tabsync-backend"
main = "worker.js"
compatibility_date = "2024-03-29"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "tabsync_logs"
database_id = "5e1510ef-35ff-44ec-b157-e7818d3fdf06" # 使用 wrangler d1 create 產生的 ID 替換這裡
